language: csharp
solution: SonarQubeIssues.sln

addons:
    sonarcloud:
        organization: "ckerkhoff"
        token:
            secure: "x8EUq02nWpozC2tUrYmuKFV3ilW6m8xEqiInipsmAuWwNLgNHjK/6Iu34NMohBBY5nxZxMWlBpFRV9zOo/npaKiBJtPLk+58rE3BdmYcjQ8NB0P1XYJKheNNaAy4QdC8rt5wcBguDkW2EtMrN0QQ2Jf2EoiVPldRJs3bF014VVUubo38oBTe29dmOuKli9LWLS0Ed2fnVPzmDl5DCuRIdJJcF3pwxtCB//CLiMxYnsxbd2glziTMIHcvojP40EeAuHtpeb89H0LR7bVPMJnCMiUk536LhVPuCqbBHLRPgA3cI53SQitsLmRtkToLQ6ASDoWJsfmRD7VNMcQf6jZiTxcFDDBVDxYxMqVJlOJL50CitO+U4pKLzr9QFfghat4SIgU0BR2ZZSUDH0oQkB1mVOBoxkceuNQZ5vQSA6TSR2EBlSCVpgOt6WKSkxFnaLx9yo/k/q1OrjxlDwTDYaZErT8dWLp41w/8S6MZV1+Ue2zQJWPv7OIWiYGpGr5yPgiZcJJfz92CqOTRnNibmUMGqYLuKblVzYPjzS8l+mDZ7eSymLj5paKqerDN9iswtu2LvCyW3MbsSRCD9nG4V1TG4muDh8cHtXmxObeaek5cH3EjsnRxAUpelXBWhXivwuvnvJgz3K9lgSWteljApzIPqwUkMlUKXopAODth4ySpL4Y="

script:
    - sonar-scanner